### ISSUE TITLE
Music files missing

### ISSUE THREAD

**Issue by hatesigningup** [Joker2770/PySolFC-snap#1]
Looks like you forgot to include the music mod files.

**Comment by Joker2770** [comment]
Maybe you could copy or move the music songs to your ~/snap/py-sol-fc/current/.PySolFC/music/ directory. 
It seems that is not working or no use from my testing before.

**Comment by hatesigningup** [comment]
That was the first thing I tried, but Snaps on Ubuntu are read only and it's not possible to modify the folder structure (I believe they're a mounted loop file system - sort of like an iso file).  No big deal, I removed this version and installed the FlatPack version which works perfectly.  Thanks anyway.
